### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by pelinquin** [jackjack-jj/jeeq#1]
Hi!

Would it be possible for you to add a 'generate_key' function so it would be possible for anyone to test your implementation.
I am usign ECDSA for signing with 521P curve (not the one used for bitcoin), and I'd like to add encryption first, then signcryption...so your code may be a good start.

Other advice; you should switch to Python3, then you don't have to add 'L' in your integers, and a few other things.

I did not understand what the b58encode/decode for ?, can't you just use b64encoding ?

Thanks

Laurent

**Comment by jackjack-jj** [comment]
Hi
Sorry for the delay I don't log in often.

I think I don't understand what you want the 'generate_key' function to do. My best guess is that you want it to create a random pair (public_key, private_key), right?

That's interesting you want to use it for another EC. I tried to make it usable for any EC but if I missed something just tell me and I'll change that.
b58encode/decode are for example Bitcoin parts so you won't need it. In the Bitcoin protocol, an address is not a point on the EC but base58('\x00'+RIPEMD160(SHA256(point on the EC))), hence the b58 thing.

Also, yes I know I should switch to Python3 but I currently don't have the time to check all the differences and learn them. I'll do it though, hopefully soon.

Thanks for your interest

**Comment by pelinquin** [comment]
I am taking few days of vacations, but I will send you my Python3 code as soon as I am back home.

Yes, I know key generation is simple, but it seems that could hep people who want to test your code….but maybe if one has already a bit coin address, it it not useful, 

OK for the base58 for bit coin, that is what I thought.

I used YOUR idea for encrypting with the 521P curve and it works perfectly…the encrypted message is a little long but that's OK. I 'm not a crypto expert, just a PhD in computer science, but it seems that you discovered a simple and nice way for encryption when you use ECDSA for signature. You should publish a paper. There are many guys in crypto who never implement there ideas (I do not know how they checks that it works!), so I am very happy to find someone who do implement crypto algo. I put last year the Python prog for "ring signature" on wikipedia…and I wish to add other ones.

Which country are you from ?

I start a few weeks ago a startup in France on free digital payment (cash, checks, smartphone), without bit coin, credit card nor NFC. There is about 20 competitors but we have really the best offer.
I am looking for people around  Europe (SEPA zone) to start this business in other countries than France. Tell me if that might interest you. 

All transaction use a ECDSA 521P signature, and I am working on using a "crypt sign" because the database is shared using a P2P network, so to insure confidentiality.

I may contact you later if you wish.

Laurent Fournier

**Comment by jackjack-jj** [comment]
You're absolutely right, I just wasn't sure about what you suggested. It's added now.

As for the length of the encrypted message, it's normal it's long with this method. Twice as long as the original message if you un-base64 it.
That's the main drawback I think. 

For the rest, you should have received an email.
